services:
  - type: web
    name: agribridge-backend
    env: node
    region: singapore
    plan: free
    buildCommand: npm install --prefix backend
    startCommand: node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DB_TYPE
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: MAX_FILE_SIZE_BYTES
        value: 10485760
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: WEATHER_API_KEY
        sync: false
