import React from "react";
import {Routes,Route} from "react-router-dom";
import {Dash,Stat} from "../components/Site";
import {crops,lands,users} from "../data";
const nav=[["/admin","Dashboard","bi-speedometer2"],["/admin/users","Users","bi-people"],["/admin/crops","Crops & Marketplace","bi-shop"],["/admin/lands","Lands","bi-map"],["/admin/reports","Reports","bi-bar-chart"],["/admin/settings","Settings","bi-gear"],["/admin/logout","Logout","bi-box-arrow-right"]];
const Card=({title,children,action})=><div className="dash-card"><div className="dash-card-head"><h6>{title}</h6>{action}</div>{children}</div>;
const Table=({head,rows})=><div className="table-responsive"><table className="table"><thead><tr>{head.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((x,j)=><td key={j}>{x}</td>)}</tr>)}</tbody></table></div>;
function Chart(){return <div className="chart"><svg viewBox="0 0 600 220" preserveAspectRatio="none"><polyline points="0,180 70,150 130,165 190,120 250,140 310,90 370,110 430,55 500,75 600,25" fill="none" stroke="currentColor" strokeWidth="5" strokeLinecap="round"/></svg></div>}
function Home(){const userStr = (() => { try { return JSON.parse(localStorage.getItem('agribridge_user') || '{}'); } catch { return {}; } })(); const name = userStr?.full_name?.trim() || 'User'; return <><div className="welcome"><div><span className="eyebrow">ADMINISTRATION</span><h2>Welcome, {name}! 🛡️</h2><p>Monitor the AgriBridge ecosystem.</p></div></div><div className="row g-3 mb-4">{[["bi-people","1,250","Total Users"],["bi-person-badge","800","Total Farmers"],["bi-cart","300","Total Buyers"],["bi-map","150","Total Lands"]].map(x=><div className="col-6 col-lg-3" key={x[2]}><Stat icon={x[0]} value={x[1]} label={x[2]}/></div>)}</div><div className="row g-4"><div className="col-lg-7"><Card title="Users Overview"><Chart/></Card></div><div className="col-lg-5"><Card title="Sales Overview"><div className="donut">62%</div><p className="text-center lead-muted">Marketplace 62% · Leasing 25% · Other 13%</p></Card></div></div></>}
function Users(){return <Card title="Manage Users"><Table head={["Name","Email","Role","Status","Actions"]} rows={users.map(u=>[u.name,u.email,u.role,<span className="badge-soft">{u.status}</span>,<><button className="btn btn-sm btn-outline-secondary me-1">Edit</button><button className="btn btn-sm btn-outline-danger">Delete</button></>])}/></Card>}
function Crops(){return <Card title="Manage Crops & Marketplace" action={<button className="btn btn-sm btn-success">Add Crop</button>}><Table head={["Crop","Category","Price","Status","Actions"]} rows={crops.map(c=>[c.name,c.category,`₹${c.price}/kg`,<span className="badge-soft">Active</span>,<><button className="btn btn-sm btn-outline-secondary me-1">Edit</button><button className="btn btn-sm btn-outline-danger">Delete</button></>])}/></Card>}
function Lands(){return <Card title="Manage Lands"><Table head={["Location","Area","Price/Year","Status","Actions"]} rows={lands.map(l=>[l.location,`${l.area} Acres`,`₹${l.price.toLocaleString()}`,<span className="badge-soft">{l.status}</span>,<><button className="btn btn-sm btn-outline-secondary me-1">Edit</button><button className="btn btn-sm btn-outline-danger">Delete</button></>])}/></Card>}
function Reports(){return <div className="row g-4"><div className="col-md-4"><Card title="Monthly Orders"><h2>₹2.8L</h2><span className="text-success">+18.2%</span></Card></div><div className="col-md-4"><Card title="New Users"><h2>126</h2><span className="text-success">+9.4%</span></Card></div><div className="col-md-4"><Card title="Lease Requests"><h2>42</h2><span className="text-success">+14.1%</span></Card></div><div className="col-12"><Card title="Reports & Analytics"><Chart/></Card></div></div>}
function Settings(){return <Card title="Settings"><form className="row g-3"><div className="col-md-6"><label>Platform Name</label><input className="form-control" defaultValue="AgriBridge"/></div><div className="col-md-6"><label>Support Email</label><input className="form-control" defaultValue="support@agribridge.com"/></div><div className="col-12"><div className="setting">Email notifications <input type="checkbox" defaultChecked/></div><div className="setting">New listing moderation <input type="checkbox" defaultChecked/></div></div><div><button className="btn btn-success">Save Settings</button></div></form></Card>}
export default function Admin(){return <Dash role="Admin" title="Admin Dashboard" items={nav}><Routes><Route index element={<Home/>}/><Route path="users" element={<Users/>}/><Route path="crops" element={<Crops/>}/><Route path="lands" element={<Lands/>}/><Route path="reports" element={<Reports/>}/><Route path="settings" element={<Settings/>}/></Routes></Dash>}