import React,{useState} from "react";
import {Routes,Route,Link} from "react-router-dom";
import {Dash,Stat,CropCard} from "../components/Site";
import {crops,orders} from "../data";
const nav=[["/buyer","Dashboard","bi-grid-1x2-fill"],["/buyer/browse","Browse Crops","bi-shop"],["/buyer/orders","My Orders","bi-bag-check"],["/buyer/cart","Cart","bi-cart3"],["/buyer/saved","Saved Items","bi-heart"],["/buyer/profile","Profile","bi-person"],["/buyer/logout","Logout","bi-box-arrow-right"]];
const Card=({title,children})=><div className="dash-card"><div className="dash-card-head"><h6>{title}</h6></div>{children}</div>;
function Orders(){return <Card title="Order History"><div className="table-responsive"><table className="table"><thead><tr><th>Order</th><th>Date</th><th>Item</th><th>Amount</th><th>Status</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td>{o.id}</td><td>{o.date}</td><td>{o.item}</td><td>₹{o.amount}</td><td><span className="badge-soft">{o.status}</span></td></tr>)}</tbody></table></div></Card>}
function Home(){const userStr = (() => { try { return JSON.parse(localStorage.getItem('agribridge_user') || '{}'); } catch { return {}; } })(); const name = userStr?.full_name?.trim() || 'User'; return <><div className="welcome"><div><span className="eyebrow">BUYER WORKSPACE</span><h2>Welcome, {name}! 🛒</h2><p>Track purchases and discover fresh produce.</p></div></div><div className="row g-3 mb-4">{[["bi-cart-check","3","Orders"],["bi-cart3","5","Cart Items"],["bi-heart","10","Saved Items"],["bi-currency-rupee","₹12,400","Spent"]].map(x=><div className="col-6 col-lg-3" key={x[2]}><Stat icon={x[0]} value={x[1]} label={x[2]}/></div>)}</div><Orders/></>}
function Browse(){const[cart,setCart]=useState(0);return <><div className="welcome"><div><span className="eyebrow">MARKETPLACE</span><h2>Browse Crops</h2><p>Fresh products from farmer listings.</p></div><span className="cart-pill">🛒 {cart} in cart</span></div><div className="row g-4">{crops.map(c=><div className="col-6 col-md-4 col-xl-3" key={c.id}><CropCard crop={c} onAdd={()=>setCart(x=>x+1)}/></div>)}</div></>}
function Cart(){return <Card title="Shopping Cart"><div className="cart-lines">{crops.map(c=><div className="cart-line" key={c.id}><span className={`thumb ${c.tone}`}>{c.emoji}</span><span><b>{c.name}</b><small>₹{c.price}/kg · Qty 1</small></span><strong>₹{c.price}</strong></div>)}</div><div className="cart-total"><span>Total Amount</span><b>₹38</b></div><button className="btn btn-success w-100">Proceed to Checkout</button></Card>}
function Saved(){return <div className="empty">♡<h5>Saved items</h5><p>Your saved crops will appear here.</p></div>}
function Profile(){return <Card title="My Profile"><form className="row g-3">{["Full Name","Email","Phone","Address"].map(x=><div className="col-md-6" key={x}><label>{x}</label><input className="form-control" defaultValue={x==="Full Name"?"Suresh":x==="Email"?"suresh@gmail.com":""}/></div>)}<div><button className="btn btn-success">Update Profile</button></div></form></Card>}
export default function Buyer(){return <Dash role="Buyer" title="Buyer Dashboard" items={nav}><Routes><Route index element={<Home/>}/><Route path="browse" element={<Browse/>}/><Route path="orders" element={<Orders/>}/><Route path="cart" element={<Cart/>}/><Route path="saved" element={<Saved/>}/><Route path="profile" element={<Profile/>}/></Routes></Dash>}