import React,{useState} from "react";
import {Routes,Route,Link} from "react-router-dom";
import {Dash,Stat} from "../components/Site";
import {crops,orders} from "../data";
const nav=[["/farmer","Dashboard","bi-grid-1x2-fill"],["/farmer/profile","My Profile","bi-person"],["/farmer/crops","My Crops","bi-box-seam"],["/farmer/add-crop","Add Crop","bi-plus-square"],["/farmer/assistant","AI Assistant","bi-robot"],["/farmer/irrigation","Irrigation","bi-droplet"],["/farmer/logout","Logout","bi-box-arrow-right"]];
const Card=({title,children,action})=><div className="dash-card"><div className="dash-card-head"><h6>{title}</h6>{action}</div>{children}</div>;
const Table=({head,rows})=><div className="table-responsive"><table className="table align-middle"><thead><tr>{head.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((x,j)=><td key={j}>{x}</td>)}</tr>)}</tbody></table></div>;
function Overview(){const userStr = (() => { try { return JSON.parse(localStorage.getItem('agribridge_user') || '{}'); } catch { return {}; } })(); const name = userStr?.full_name?.trim() || 'User'; return <><div className="welcome"><div><span className="eyebrow">FARMER WORKSPACE</span><h2>Welcome, {name}! 👋</h2><p>Here’s what is happening with your farm today.</p></div></div><div className="row g-3 mb-4">{[["bi-box-seam","12","Crops"],["bi-shop","8","Active Listings"],["bi-cart-check","5","Orders"],["bi-currency-rupee","₹45,000","Revenue"]].map(x=><div className="col-6 col-lg-3" key={x[2]}><Stat icon={x[0]} value={x[1]} label={x[2]}/></div>)}</div><div className="row g-4"><div className="col-lg-7"><Card title="Recent Listings" action={<Link to="/farmer/crops">View All</Link>}><Table head={["Crop","Quantity","Price","Status"]} rows={crops.map(c=>[c.name,`${c.qty} kg`,`₹${c.price}/kg`,<span className="badge-soft">Active</span>])}/></Card></div><div className="col-lg-5"><Card title="Recent Orders"><Table head={["Order","Item","Amount"]} rows={orders.map(o=>[o.id,o.item,`₹${o.amount}`])}/></Card></div></div></>}
function Profile(){return <Card title="My Profile"><form className="row g-3">{["Full Name","Email","Phone","Location"].map(x=><div className="col-md-6" key={x}><label>{x}</label><input className="form-control" defaultValue={x==="Full Name"?"Ramesh":x==="Email"?"ramesh@gmail.com":x==="Location"?"Guntur, Andhra Pradesh":""}/></div>)}<div><button className="btn btn-success">Update Profile</button></div></form></Card>}
function Crops(){return <Card title="My Crop Listings" action={<Link to="/farmer/add-crop" className="btn btn-sm btn-success">+ Add Crop</Link>}><Table head={["Crop","Quantity","Price","Status","Actions"]} rows={crops.map(c=>[c.name,`${c.qty} kg`,`₹${c.price}/kg`,<span className="badge-soft">Active</span>,<><button className="btn btn-sm btn-outline-secondary me-1">Edit</button><button className="btn btn-sm btn-outline-danger">Delete</button></>])}/></Card>}
function AddCrop(){const[done,setDone]=useState(false);return <Card title="Add Crop"><form className="row g-3" onSubmit={e=>{e.preventDefault();setDone(true)}}>{["Crop Name","Category","Quantity (kg)","Price per kg"].map(x=><div className="col-md-6" key={x}><label>{x}</label><input required className="form-control" placeholder={x}/></div>)}<div className="col-12"><label>Description</label><textarea className="form-control" rows="4"/></div><div className="col-12"><label>Image Upload</label><input type="file" className="form-control"/></div><div><button className="btn btn-success px-4">Submit Crop</button></div></form>{done&&<div className="alert alert-success mt-3">Crop listing added successfully.</div>}</Card>}
function Assistant(){return <Card title="AI Farming Assistant"><div className="assistant"><div className="ai-msg"><span>AI</span>Hello Farmer! How can I help you today?</div><div className="suggestions">{["Crop Recommendation","Pest Detection","Fertilizer Suggestion","General Advice"].map(x=><button key={x}>{x}</button>)}</div><div className="d-flex gap-2"><input className="form-control" placeholder="Type your question..."/><button className="btn btn-success">➤</button></div></div></Card>}
function Irrigation(){return <div className="row g-4"><div className="col-lg-7"><Card title="Smart Irrigation"><div className="irrigation"><div><small>Field: Tomato Field</small><h1>45% <small>(Normal)</small></h1><p>Soil Moisture</p><div className="progress"><div className="progress-bar" style={{width:"45%"}}/></div></div><div>🌱💧</div></div><div className="recommend">💡 <span><b>Irrigation Recommendation</b><small>Water your field in next 12 hours.</small></span></div></Card></div><div className="col-lg-5"><Card title="Water Required"><div className="big-number">20 <small>Liters / m²</small></div><p className="lead-muted">Based on current moisture and crop profile.</p></Card></div></div>}
export default function Farmer(){return <Dash role="Farmer" title="Farmer Dashboard" items={nav}><Routes><Route index element={<Overview/>}/><Route path="profile" element={<Profile/>}/><Route path="crops" element={<Crops/>}/><Route path="add-crop" element={<AddCrop/>}/><Route path="assistant" element={<Assistant/>}/><Route path="irrigation" element={<Irrigation/>}/></Routes></Dash>}